### ISSUE TITLE
heroku issue on selfhost

### ISSUE THREAD

**Issue by kekkodance** [brandongallagher1999/1337x-Bot-Go#17]
i have this issue where the bot i'm trying to host just spits out some html about heroku
![image](https://user-images.githubusercontent.com/53054786/166824734-a66e6c04-e4ba-4ff7-a7a9-32105c0046e3.png)
if the bot is supposed to be hosted on my own machine, why would it contact heroku?

**Comment by brandongallagher1999** [comment]
Honestly, I do not know. However, you don't have a config.yaml inside of
/config/ which means the bot won't run

**Comment by kekkodance** [comment]
apart from the heroku issue, i do seem to have a config file in the config folder but it doesnt detect it 
![image](https://user-images.githubusercontent.com/53054786/166827064-0ff4e431-8176-4e5c-afdc-e8eac6d7253e.png)

**Comment by kekkodance** [comment]
i am utterly retarded, didnt run docker compose build

**Comment by brandongallagher1999** [comment]
All good, that's what I figured :) (the docker compose part)

**Comment by kekkodance** [comment]
and now im getting this funny issue
![image](https://user-images.githubusercontent.com/53054786/166828458-d0f8a02e-6fa9-40f8-bff5-a254f0960466.png)

**Comment by kekkodance** [comment]
could it be that the flaresolver instance is running on heroku and it cant call back anymore for some reason?

**Comment by brandongallagher1999** [comment]
Investigating right now.

**Comment by kekkodance** [comment]
i think this is the reason why the bot sometimes failed, having one heroku instance running for everyone who hosts it + when the prehosted bot was online

**Comment by brandongallagher1999** [comment]
nope, that would not be possible. They can't conflict in that regard.

**Comment by brandongallagher1999** [comment]
Trying to get this running locally.

**Comment by kekkodance** [comment]
> nope, that would not be possible. They can't conflict in that regard.

i'm not talking about conflicts, i'm talking about the heroku thingie getting overloaded

**Comment by brandongallagher1999** [comment]
@kekkodance 

Fixed it. Also adding a .help command for convenience. 
![image](https://user-images.githubusercontent.com/36753063/166833531-9d8cf9ea-d517-491b-bb38-712f0f91097b.png)

**Comment by kekkodance** [comment]
what was the issue?

**Comment by brandongallagher1999** [comment]
> what was the issue?

Calling torrent-service didn't have the port. I think I ended up adding the DNS name call without port and pushed to master without realizing it. Also had an older instance running on the cloud.

Making a push to master soon.

**Comment by kekkodance** [comment]
> Also had an older instance running on the cloud.


i knew this because the torrents still showed | at the end of them

**Comment by brandongallagher1999** [comment]
Apologies for the long wait. It's all running locally, and should run given a config.yaml file. You're good to go. @kekkodance

**Comment by brandongallagher1999** [comment]
![image](https://user-images.githubusercontent.com/36753063/166836900-9062f9b3-1ccd-402b-a7fa-06522acaae70.png)

**Comment by kekkodance** [comment]
i know the issue is closed and all, but the new added commands dont seem to work even after a git pull and a rebuild of the docker instance, the torrent command works so i know i updated
![image](https://user-images.githubusercontent.com/53054786/166887636-73b1014e-583c-4e16-992a-6b347eba9eb5.png)
(i also found that the max links per query config string doesnt seem to change anything or at least doesnt go more than 10 results?)
